### ISSUE TITLE
Windows discovering avahi

### ISSUE THREAD

**Issue by brtthomp** [watson/bonjour#40]
I have a linux machine running the avahi-daemon service that I am trying to discover with my windows 10 machines using this bonjour plugin.  I seem to be having issues when using a windows 10 tablet (Surface Pro).  The bonjour plugin isn't able to find any services whereas if I run bonjour browser (https://hobbyistsoftware.com/bonjourbrowser) the bonjour services are visible.  I originally thought this might be a firewall issue but if the bonjour browser is discovering them I would think otherwise.

It also doesn't seem to be specifically windows 10 related as I have other windows 10 machines that are working just fine.  This happens on multiple different Surface Pro tablets as well.

Any ideas?

**Comment by thosil** [comment]
Could you drop a piece of code?
Or trace with Wireshark?

**Comment by brtthomp** [comment]
I'm using pretty simple code:

`const bonjour = require('bonjour')();

bonjour.find({}, function(service) {
    console.log(service);
});`

I could link a wireshark but it would be empty because it seems like the initial mdns query is never sent across the wire.  Even doing a TCP dump on the device itself doesn't show anything.  I dug a little deeper and traced the query sending all the way to dgram.js which seems to say it successfully sent the 46 bytes without error though nothing still shows up.

**Comment by brtthomp** [comment]
I'm going to close this.  It seems to be with multicast-dns that is being used that doesn't currently support multiple interfaces.

https://github.com/mafintosh/multicast-dns/issues/41
