### ISSUE TITLE
Registry.unpublishAll won t invoke the callback if the records are empty

### ISSUE THREAD

**Issue by mh-cbon** [watson/bonjour#8]
Hi,

Small typo at 
https://github.com/watson/bonjour/blob/b0c7842105ee8115e642dd3c075415e18073293e/lib/registry.js#L176

I d say it should be fixed like this

```js
if (records.length === 0) return cb && cb();
```

**Comment by watson** [comment]
@mh-cbon thanks for reporting this :smiley: I've fixed it in v3.2.1

**Comment by mh-cbon** [comment]
cool, thanks, i ll update on my side !
